use axum::{
    routing::{delete, get, post, put},
    Router,
};

use crate::core::app_state::AppState;
use crate::handlers::{admin, approval, auth, calendar, company, dashboard, document, employee, notification, oauth2, payroll, portal, report, settings, team};

pub fn create_router(state: AppState) -> Router {
    let api = Router::new()
        // Auth
        .route("/auth/login", post(auth::login))
        .route("/auth/me", get(auth::me))
        .route("/auth/refresh", post(auth::refresh_token))
        .route("/auth/logout", post(auth::logout))
        .route("/auth/forgot-password", post(auth::forgot_password))
        .route("/auth/reset-password", post(auth::reset_password))
        .route("/auth/validate-reset-token", post(auth::validate_reset_token))
        .route("/auth/switch-company", put(auth::switch_company))
        .route("/auth/my-companies", get(auth::my_companies))
        // OAuth2
        .route("/auth/oauth2/providers", get(oauth2::list_providers))
        .route("/auth/oauth2/google/authorize", get(oauth2::google_authorize))
        .route("/auth/oauth2/google/callback", get(oauth2::google_callback))
        .route("/auth/oauth2/google/link", post(oauth2::link_google))
        .route("/auth/oauth2/accounts", get(oauth2::my_linked_accounts))
        .route("/auth/oauth2/accounts/:provider", delete(oauth2::unlink_provider))
        // Admin (super_admin)
        .route("/admin/companies", get(admin::list_companies).post(admin::create_company))
        .route("/admin/companies/:id", put(admin::update_company))
        .route("/admin/users", get(admin::list_users).post(admin::create_user))
        .route("/admin/users/:id", put(admin::update_user).delete(admin::delete_user))
        .route("/admin/users/:id/companies", put(admin::update_user_companies))
        .route("/admin/password-resets", get(admin::list_password_resets))
        .route("/admin/password-resets/count", get(admin::count_pending_resets))
        .route("/admin/password-resets/:id/approve", put(admin::approve_password_reset))
        .route("/admin/password-resets/:id/reject", put(admin::reject_password_reset))
        // Employees
        .route("/employees", get(employee::list).post(employee::create))
        .route("/employees/:id", get(employee::get).put(employee::update).delete(employee::delete))
        .route("/employees/:id/salary-history", get(employee::salary_history))
        .route("/employees/:id/tp3", post(employee::create_tp3))
        // Payroll Groups
        .route("/payroll-groups", get(payroll::list_groups))
        // Payroll Runs
        .route("/payroll/run", post(payroll::process))
        .route("/payroll/runs", get(payroll::list_runs))
        .route("/payroll/runs/:id", get(payroll::get_run))
        .route("/payroll/runs/:id/items", get(payroll::get_items))
        .route("/payroll/runs/:id/approve", put(payroll::approve_run))
        .route("/payroll/runs/:id/lock", put(payroll::lock_run))
        // Documents (static routes before :id)
        .route("/documents", get(document::list).post(document::create))
        .route("/documents/categories", get(document::list_categories).post(document::create_category))
        .route("/documents/expiring", get(document::expiring))
        .route("/documents/:id", get(document::get).put(document::update).delete(document::delete))
        // Settings
        .route("/settings", get(settings::list).put(settings::bulk_update))
        .route("/settings/:category/:key", get(settings::get).put(settings::update))
        // Company
        .route("/company", get(company::get).put(company::update))
        .route("/company/stats", get(company::stats))
        // Employee Portal (self-service)
        .route("/portal/profile", get(portal::get_profile))
        .route("/portal/payslips", get(portal::list_payslips))
        .route("/portal/leave/types", get(portal::leave_types))
        .route("/portal/leave/balances", get(portal::leave_balances))
        .route("/portal/leave/requests", get(portal::leave_requests).post(portal::create_leave))
        .route("/portal/leave/requests/:id/cancel", put(portal::cancel_leave))
        .route("/portal/teams", get(portal::my_teams))
        .route("/portal/team-calendar", get(portal::team_calendar))
        .route("/portal/holidays", get(portal::portal_holidays))
        .route("/portal/claims", get(portal::list_claims).post(portal::create_claim))
        .route("/portal/claims/:id/submit", put(portal::submit_claim))
        .route("/portal/claims/:id", delete(portal::delete_claim))
        // Overtime (portal)
        .route("/portal/overtime", get(portal::list_overtime).post(portal::create_overtime))
        .route("/portal/overtime/:id/cancel", put(portal::cancel_overtime))
        // File uploads
        .route("/uploads", post(portal::upload_file))
        .route("/uploads/:filename", get(portal::serve_upload))
        // Dashboard
        .route("/dashboard/summary", get(dashboard::summary))
        // Notifications
        .route("/notifications", get(notification::list))
        .route("/notifications/count", get(notification::count))
        .route("/notifications/read-all", put(notification::mark_all_read))
        .route("/notifications/:id/read", put(notification::mark_read))
        // Approval Workflows (admin)
        .route("/approvals/leave", get(approval::list_leave_requests))
        .route("/approvals/leave/:id/approve", put(approval::approve_leave))
        .route("/approvals/leave/:id/reject", put(approval::reject_leave))
        .route("/approvals/claims", get(approval::list_claims))
        .route("/approvals/claims/:id/approve", put(approval::approve_claim))
        .route("/approvals/claims/:id/reject", put(approval::reject_claim))
        // Overtime approvals (admin)
        .route("/approvals/overtime", get(approval::list_overtime))
        .route("/approvals/overtime/:id/approve", put(approval::approve_overtime))
        .route("/approvals/overtime/:id/reject", put(approval::reject_overtime))
        // Calendar (admin)
        .route("/calendar/holidays", get(calendar::list_holidays).post(calendar::create_holiday))
        .route("/calendar/holidays/:id", get(calendar::get_holiday).put(calendar::update_holiday).delete(calendar::delete_holiday))
        .route("/calendar/import-ics", post(calendar::import_ics))
        .route("/calendar/import-ics-file", post(calendar::import_ics_file))
        .route("/calendar/working-days", get(calendar::get_working_days).put(calendar::update_working_days))
        .route("/calendar/month", get(calendar::get_month_calendar))
        // Teams (admin)
        .route("/teams", get(team::list_teams).post(team::create_team))
        .route("/teams/:id", get(team::get_team).put(team::update_team).delete(team::delete_team))
        .route("/teams/:id/members", get(team::list_members).post(team::add_member))
        .route("/teams/:team_id/members/:employee_id", delete(team::remove_member))
        // Reports (admin)
        .route("/reports/payroll-summary", get(report::payroll_summary))
        .route("/reports/payroll-department", get(report::payroll_by_department))
        .route("/reports/leave", get(report::leave_report))
        .route("/reports/claims", get(report::claims_report))
        .route("/reports/statutory", get(report::statutory_report));

    Router::new().nest("/api", api).with_state(state)
}
